<a href="https://colab.research.google.com/github/nsharan2000/Project-AgroCaptain/blob/main/plant_yield_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# this is a code that is  influenced from the resource: https://github.com/Priyabrata017/Crop-prediction-using-Machine-Learning/blob/master/Crop_pred.py;


# objective: predict the type of crop that is suitable for the agricultural land based on sensor values of the temperature

In [ ]:
#importing the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#Reading the csv file
data=pd.read_csv('/content/drive/MyDrive/archive/cpdata.csv')
print(data.head(1))

#Creating dummy variable for target i.e label
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.drop('label', axis=1,inplace=True)
print('The data present in one row of the dataset is')
print(data.head(1))
train=data.iloc[:, 0:4].values
test=data.iloc[: ,4:].values

#Dividing the data into training and test set
X_train,X_test,y_train,y_test=train_test_split(train,test,test_size=0.3, random_state = 22)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Importing Decision Tree classifier
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()

#Fitting the classifier into training set
clf.fit(X_train,y_train)
pred=clf.predict(X_test)
print("pred\n",pred)
print("X_test\n",X_test)
print("Y_test\n",y_test)

from sklearn.metrics import accuracy_score
# Finding the accuracy of the model
a=accuracy_score(y_test,pred)
print("The accuracy of this model is: ", a*100)

#Using firebase to import data to be tested
# from firebase import firebase
# firebase =firebase.FirebaseApplication('https://cropit-eb156.firebaseio.com/')
# tp=firebase.get('/Realtime',None)

# ah=tp['Air Humidity']
# atemp=tp['Air Temp']
# shum=tp['Soil Humidity']
# pH=tp['Soil pH']
# rain=tp['Rainfall']


# l=[]
# l.append(ah)
# l.append(atemp)
# l.append(pH)
# l.append(rain)
# predictcrop=[l]



   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
The data present in one row of the dataset is
   temperature   humidity        ph  ...  rice  watermelon  wheat
0    20.879744  82.002744  6.502985  ...     1           0      0

[1 rows x 34 columns]
pred
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
X_test
 [[-0.92086783  0.05130139 -0.33937724 -0.53006505]
 [-0.71747375  1.1937749  -0.59263225  0.02203247]
 [ 0.38375235  0.12453186  0.36958476 -0.68171535]
 ...
 [-0.04386827  0.87550857  0.6216907  -0.92146144]
 [ 1.13471643  0.71187015 -0.72424393 -0.58006246]
 [-0.91746399  0.63956459  1.55020497  2.35680151]]
Y_test
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
The accuracy of this model is:  90.0


In [ ]:
np.array(data.iloc[: ,4:].columns)

array(['Black gram', 'Chickpea', 'Coconut', 'Coffee', 'Cotton',
       'Ground Nut', 'Jute', 'Kidney Beans', 'Lentil', 'Moth Beans',
       'Mung Bean', 'Peas', 'Pigeon Peas', 'Rubber', 'Sugarcane', 'Tea',
       'Tobacco', 'apple', 'banana', 'grapes', 'maize', 'mango', 'millet',
       'muskmelon', 'orange', 'papaya', 'pomegranate', 'rice',
       'watermelon', 'wheat'], dtype=object)

In [ ]:
type(X_test[:3])

numpy.ndarray

In [ ]:
# # # Putting the names of crop in a single list
# crops=['rice','wheat','mungbean','Tea','millet','maize','lentil','jute','cofee','cotton','ground nut','peas','rubber',  
#        'sugarcane','tobacco','kidney beans','moth beans','coconut','blackgram','adzuki beans',
#        'pigeon peas','chick peas','banana','grapes','apple','mango','muskmelon','orange','papaya','watermelon','pomegranate']


# #sample values for testing
# 20.2801937	82.1235421	7.236705436	191.9535738	rice
# 28.14720892	83.8001509	6.647965508	37.44800463	Mung Bean
# 25.19192419,	66.6902901,	5.913664501,	78.06639649	maize
# 17.47500984,	16.54314829,	6.18042747,	93.35034262	Chickpea
# 28.89578588	94.78993038	6.286515359	23.0362503	muskmelon

crops = np.array(data.iloc[: ,4:].columns);

#Predicting the crop
# predictions = clf.predict(X_test[:10])
# print(X_test[3])
#print(clf.predict(predictcrop))

inputval = sc.transform([[17.47500984,	16.54314829,	6.18042747,	93.35034262]]) #sample values for chickpeas
predictions = clf.predict(inputval)

count=0
for i in range(0,30):
    #print(predictions[3][i]);
    if(predictions[0][i]==1):
        c=crops[i]
        count=count+1
        break;
    i=i+1
if(count==0):
    print("irregular data to predict. But a good suggestion would be to plant rice")
else:
    print('The predicted crop is %s'%c)

# #Sending the predicted crop to database
# cp=firebase.put('/croppredicted','crop',c)

The predicted crop is Chickpea
